# Generated by Django 5.0.3 on 2024-04-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_tender_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
