# Generated by Django 5.0.3 on 2024-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_tender_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Location',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
