# Generated by Django 5.0.3 on 2024-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_alter_tender_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Location',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
