# Generated by Django 5.0.3 on 2024-04-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0006_alter_tender_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Winning_Price',
            field=models.CharField(max_length=20),
        ),
    ]
