# Generated by Django 5.0.3 on 2024-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0007_alter_tender_winning_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
