# Generated by Django 5.0.3 on 2024-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0010_alter_tender_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='Tender_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
