# Generated by Django 5.0.3 on 2024-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0011_tender_tender_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Tender_number',
            field=models.CharField(max_length=200),
        ),
    ]
