# Generated by Django 5.0.3 on 2024-04-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0012_alter_tender_tender_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Date',
            field=models.DateField(verbose_name=''),
        ),
    ]
