# Generated by Django 5.0.3 on 2024-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_alter_tender_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='Date',
            field=models.DateField(),
        ),
    ]
