# Generated by Django 5.0.3 on 2024-04-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_alter_tender_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='Remarks',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
